Eng 15149.rectify.calcite.branch (#5833)
* Revert "ENG-15030 Query with many joins drains during planning (#5805)"

This reverts commit a27f42b6705f1d03f1a977e05dd779cc510db010.

Because Jenkins test is OOM:
java.lang.OutOfMemoryError: GC overhead limit exceeded

* Fix Jenkins failure on ENG-15030

Because Jenkins JVM allocated smaller memory.
Set JVM heap threshold from 85% to 80% to please Jenkins.

* The fix

* ENG-15078, adding asserts and debug level logs to monitor export sequence number during rollbacks. (#5832)

Change-Id: I91cf684c63f0035ecf28b00d540ed69f3af96492

* Added missing copyrights

* Addressed PR feedback