Revert "ENG-15030 Query with many joins drains during planning (#5805)"
This reverts commit a27f42b6705f1d03f1a977e05dd779cc510db010.

Because Jenkins test is OOM:
java.lang.OutOfMemoryError: GC overhead limit exceeded